title: Gen Zou # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  CS PhD Degree, UNB, Canada
  <br />
  CS Master Degree, Tsinghua Univ., China
  
show_downloads: false
theme: jekyll-theme-minimal
google_analytics: UA-143971986-1 # your Google Analytics tracking ID here
